version: '2'

networks:
  codespace:
    driver: bridge

services:
  docker:
    image: codespaces/docker-control:v0.3.0
    ports:
      - "8000:8000"
      - "80:80"
    environment:
      JAVA_ARGS: "-Xms256m -Xmx256m -XX:MaxPermSize=256m"
    volumes:
#      - /control:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge
    container_name: docker
    domainname: rns.com
    hostname: docker
    restart: always
